<a href="https://colab.research.google.com/github/KimDoye1109/AI-programming/blob/main/week2_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Tensor 객체의 attributes: ndim, shape, dtype https://ds31x.tistory.com/216

In [ ]:
import numpy as np
import tensorflow as tf
import torch

In [ ]:
np.__version__

'1.25.2'

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
torch.__version__

'2.2.1+cu121'

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


In [ ]:
import importlib

# 1. Tensor 생성하기
- list나 tuple로 narray 생성
- dtype: data type of element.
  - float64: numpy의 기본 값
  - uint8: 이미지 프로세싱에 주로 사용, unsigned int(부호가 +, 0)
  - int8: signed int(부호 +,0,-)
  - float32: float(32bit)

tensor를 추상화하는 대표적인 class: ndarray(numpy), tensor(pytorch), constant or Variable (tensorflow)


대표적인 attribute(부속물):
- dtype: the datatype of element.
- ndim: 차원의 수, (=rank)
- shape: ndim의 객수로 구성된 sequencty type의 인스턴스로 각 축의 크기



pytorch와 numpy의 경우, tensor를 추상화하고 있는 tensor와 ndarray를 제공 -> 상호호환 가능.


In [ ]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))
print(a)

<class 'tuple'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


= tuple과 numpy.ndarry 차이

tuple은 불변하며 다른 데이터 타입을 포함가능, 1차원, 파이썬의 내장 데이터 구조

ndarray는 변화하며 동일 데이터 타입만을 포함, 다차원, Numpy 라이브러리에서 제공

In [ ]:
print(a.ndim)
print(a.shape) #각 차원의 수
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(6,)
8
6
int64


In [ ]:
  a = np.array([1.,2.,3.])
  print(a.dtype)
  a = np.array([1.,2.,3.],dtype = int)
  print(a.dtype)
  a = np.array([1.,2.,3.], dtype = float)
  print(a.dtype)

float64
int64
float64


tensorflow에서의 tensor 생성하기(tensor에서 itemsize와 size는 제공x)

In [ ]:
tensor = tf.constant(t) #t=(1,2,3,4,5,6)
print(tf.rank(tensor)) #핵심!!
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int32'>


In [ ]:
tensor = tf.constant(t)
print(tf.Variable(tensor)) #차원rank = ndim
#print(tensor.ndim)
#print(tensor.shape)
#print(tensor.itemsize) -error. not supported
#print(tenosr.size) -error. not supported
print(tensor.dtype)
tensor

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
p = torch.tensor(t)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size()) #not attribute, but method, 핵심!!
print(p.dtype)

1
torch.Size([6])
8
torch.Size([6])
torch.int64


In [ ]:
p= torch.tensor(t)
print(p.ndim,type(p.ndim))
print(p.shape,type(p.shape))
print(p.itemsize,type(p.itemsize))
print(p.size(),type(p.size())) #not attribute but method
print(p.dtype,type(p.dtype))

1 <class 'int'>
torch.Size([6]) <class 'torch.Size'>
8 <class 'int'>
torch.Size([6]) <class 'torch.Size'>
torch.int64 <class 'torch.dtype'>


# 1-0. 기본 dtype
numpy의 경우, float64와 int64

tensorflow의 경우, float32와 int32

torch의 경우, float32와 int64

In [ ]:
print(np.array([1., 2., 3.]).dtype)
print(np.array([1, 2, 3]).dtype)
print(tf.constant([1., 2., 3.]).dtype)
print(tf.constant([1, 2, 3]).dtype)
print(torch.tensor([1., 2., 3.]).dtype)
print(torch.tensor([1, 2, 3]).dtype)

float64
int64
<dtype: 'float32'>
<dtype: 'int32'>
torch.float32
torch.int64


# 1-1. multi-dimensionial array!


In [ ]:
a = np.array([range(i, i+3) for i in [2,3,4]])
print(a.ndim)
print(a.shape) #행, 열
print(a.itemsize)
print(a.size)
print(a.dtype)
a

2
(3, 3)
8
9
int64


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.dtype)
print(tensor.shape)
tensor

tf.Tensor(2, shape=(), dtype=int32)
2
<dtype: 'int64'>
(3, 3)


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])>

In [ ]:
p = torch.tensor(a)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size()) #not attribute but method
print(p.dtype)
p

2
torch.Size([3, 3])
8
torch.Size([3, 3])
torch.int64


tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

# 1-2. tensor를 특정 값으로 초기화하기
zeros, ones, and full (or fill)

In [ ]:
a = np.zeros((3,2)) #dtype = float64
#a = np.zeros(shape=(4,4),dtype=np.unit8)
print(a.dtype)
a

float64


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a_tf = tf.zeros(shape = (3,2)) #기본 dtype = float 32, tf.zeros((3,2)) 가
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a_tf.numpy()

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
p = torch.zeros(size = (3,2)) #없는 것도 X, shape X
print(p.dtype)
p
# p.numpy()도 가능

torch.float32


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a = np.ones((4, 2, 3))
print(a.dtype)
a

float64


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a_tf = tf.ones(shape = (4,2,3))
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
p = torch.ones(size = (4,2,3))
print(p.dtype)
p

torch.float32


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
a = np.full((1,3),255) #행, 열, 채우고 싶은 숫자
print(a.dtype)
a

int64


array([[255, 255, 255]])

In [ ]:
a_tf = tf.fill((1,3),255) #not full, but fill
print(a_tf.dtype) #default int 32
a_tf

<dtype: 'int32'>


<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[255, 255, 255]], dtype=int32)>

In [ ]:
p = torch.full((1,3),255)
print(torch.dtype)
p

<class 'torch.dtype'>


tensor([[255, 255, 255]])

# 1-3. 기존의 tensor와 같은 shape의 새로운 tensor 생성
- 기존의 ndarray와 같은 shape를 가지는 ndarray 생성(torch의 tensor도 유사)
  - zeros_like, ones_like, and full_like
- tf의 경우는 다음과 같음.
  - zeros_like, ones_like, and fill

In [ ]:
s = np.array([[1, 2, 3], [4, 5, 6]])
print(s.shape, s.dtype)

a = np.zeros_like(s)
print(a.shape, a.dtype)
a

(2, 3) int64
(2, 3) int64


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.ones_like(s)
print(a.shape, a.dtype)
a

(2, 3) int64


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.full_like(s, 3.0)
print(a.shape, a.dtype)
a

(2, 3) int64


array([[3, 3, 3],
       [3, 3, 3]])

= np.full_like(s, 3.0)에서 3.0의 의미는?
채워지는 숫자

In [ ]:
s = tf.constant([[1,2,3],[4,5,6]])
print(s.shape, s.dtype)

a = tf.zeros_like(s)
print(a.shape, a.dtype)
a

(2, 3) <dtype: 'int32'>
(2, 3) <dtype: 'int32'>


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
b = tf.ones_like(s)
print(b.shape, b.dtype)
b

(2, 3) <dtype: 'int32'>


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
c = tf.fill(s.shape, 3.0)
print(c.shape, c.dtype)
c

(2, 3) <dtype: 'float32'>


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [ ]:
p = torch.tensor([[1,2,3], [4,5,6]])
print(p.shape, p.dtype)

a = torch.zeros_like(p)
print(a.shape, a.dtype)
a

torch.Size([2, 3]) torch.int64
torch.Size([2, 3]) torch.int64


tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
b = torch.ones_like(p)
print(b.shape, b.dtype)
b

torch.Size([2, 3]) torch.int64


tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
c = torch.full_like(p, 3.0)
print(c.shape, c.dtype)
c

torch.Size([2, 3]) torch.int64


tensor([[3, 3, 3],
        [3, 3, 3]])

#1-4. 기타 다른 tensor 생성 방법들.

In [ ]:
print(range(0, 10, 1)) #only integer
print(np.arange(0,1,0.1))

range(0, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a = np.arange(0, 24, 2).reshape(3,4)
print(a.dtype)
a

int64


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a_tf = tf.constant(tf.range(0,6,0.5),shape=(3,4)) #float도 가능
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]], dtype=float32)>

In [ ]:
a_torch = torch.arange(0,24,2).reshape(3,4)
print(a_torch.dtype)
a_torch

torch.int64


tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])

In [ ]:
a = torch.arange(0., 1., 0.1)
print(a.dtype)
a

torch.float32


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])

In [ ]:
a = np.linspace(1,5,6) #linspace 일정한 간격으로 숫자 추출
print(a.dtype)
print(a)

a_tf = tf.linspace(1, 5, 6)
print(a_tf.dtype)
b_tf = tf.dtypes.cast(a_tf, tf.float32)
print(b_tf.dtype)
print(b_tf)
a_torch = torch.linspace(1,5,6)
print(a_torch.dtype)
print(a_torch)

float64
[1.  1.8 2.6 3.4 4.2 5. ]
<dtype: 'float64'>
<dtype: 'float32'>
tf.Tensor([1.  1.8 2.6 3.4 4.2 5. ], shape=(6,), dtype=float32)
torch.float32
tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])


eye = 사선 정렬

In [ ]:
a = np.eye(5)
print(a.dtype)
print(a)

a_tf = tf.eye(5)
print(a_tf.dtype)
print(a_tf)

a_torch = torch.eye(5)
print(a_torch.dtype)
print(a_torch)

float64
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<dtype: 'float32'>
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
torch.float32
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
a = np.empty((4,2))
print(a.dtype)
print(a)

#tf는 not working. ->

a_torch = torch.empty((4,2))
print(a_torch.dtype)
print(a_torch)

float64
[[4.82362356e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
torch.float32
tensor([[-9.2414e-35,  4.3796e-41],
        [-9.2414e-35,  4.3796e-41],
        [ 4.4842e-44,  0.0000e+00],
        [ 1.7937e-43,  0.0000e+00]])


#1-5. 난수로 구성된 tensor 생성
- numpy.random과 torch
  - rand([d0 [,d1, [...,dn]): 0~1사이의 수들이 균일한 확률로 선택되어 반환됨.
    - d0,...dn: 난수로 구성된 ndarray의 shape를 지정하는데 사용됨.
  - randn([d0 [,d1, [...,dn]):
  μ=0,σ=1인 정규분포를 따르는 난수 반환.
* tensorflow
  * random.uniform(shape, minval, maxval)
  * random.normal(shape, mean,stddev)

In [ ]:
a = np.random.rand(3,4)
print(a.dtype)
a

float64


array([[0.76324958, 0.23096662, 0.77504757, 0.79478568],
       [0.52187963, 0.85369506, 0.6152377 , 0.37671067],
       [0.273345  , 0.28980482, 0.04526833, 0.8255391 ]])

In [ ]:
a_tf = tf.random.uniform(shape = (3,4), minval =0., maxval = 1.)
a_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.94594944, 0.30062687, 0.9695028 , 0.4040258 ],
       [0.6521095 , 0.18838477, 0.40089703, 0.24992824],
       [0.6556233 , 0.14316332, 0.37664104, 0.78637433]], dtype=float32)>

In [ ]:
a_torch = torch.rand(3,4)
print(a_torch.dtype)
a_torch

torch.float32


tensor([[0.2629, 0.8924, 0.3981, 0.5881],
        [0.4294, 0.1817, 0.0276, 0.3449],
        [0.1011, 0.2900, 0.9910, 0.4782]])

In [ ]:
a = np.random.randn(3,4)
print(a.shape)
print(np.mean(a), np.std(a))
a

(3, 4)
-0.39094999158703253 0.9461433490159392


array([[-0.75748857,  0.14686536,  0.69822254,  0.17632216],
       [ 1.34489329,  0.33682223, -1.56761431, -0.95046947],
       [-0.05523562, -1.00440559, -2.02352675, -1.03578516]])

In [ ]:
a_tf = tf.random.normal(shape = (3,4), mean = 0, stddev = 1.0)
print(a_tf.shape)
print(tf.math.reduce_mean(a_tf), tf.math.reduce_std(a_tf))
a_tf

(3, 4)
tf.Tensor(0.35313776, shape=(), dtype=float32) tf.Tensor(1.2470443, shape=(), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.370913  ,  1.4525361 ,  2.6304553 , -0.5394712 ],
       [-0.04402696, -0.5386813 ,  1.5687238 , -0.7645214 ],
       [-2.038817  ,  1.0158861 ,  0.46850085,  1.3979818 ]],
      dtype=float32)>

In [ ]:
a_torch = torch.randn(3,4)
print(a_torch.dtype)
print(torch.mean(a_torch), torch.std(a_torch))
a_torch

torch.float32
tensor(-0.4062) tensor(1.0262)


tensor([[-1.2141,  1.8756, -1.0496, -1.2371],
        [-1.0595, -0.7463, -0.3387, -0.6214],
        [ 0.1948,  0.0052, -1.6623,  0.9791]])